# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe23361980700adfeb250fc7a849771e6dc49357d4ce74fd995a3c45e82ce5e3db310a65d6831d57f06aa607778aa1c1f719521bafb3f113c87ebd130fe106a8

test:
  secret_key_base: ca5aa340b93a39c0af78beafb23828ade4fbf5b058de756af1d34eaea5ff4ccbec7021626431629e6edb0849cacb6143bacbbfbd268820442236aa251f4ea651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
